name: default-workflows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  oxlint:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npx --yes oxlint@0.0.22

  unit-test:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: yarn --frozen-lockfile

      - run: yarn test
